# Generated by Django 5.2.6 on 2026-07-07 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_banner_image_user_is_private_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_search', models.BooleanField(default=True)),
                ('hide_from_search_engines', models.BooleanField(default=False)),
                ('hide_followers_list', models.BooleanField(default=False)),
                ('allow_story_comments', models.CharField(choices=[('everyone', 'Everyone'), ('registered', 'Registered users'), ('followers', 'Followers only'), ('noone', 'No one')], default='everyone', max_length=20)),
                ('allow_poem_comments', models.CharField(choices=[('everyone', 'Everyone'), ('registered', 'Registered users'), ('followers', 'Followers only'), ('noone', 'No one')], default='everyone', max_length=20)),
                ('allow_messages', models.CharField(choices=[('everyone', 'Everyone'), ('registered', 'Registered users'), ('followers', 'Followers only'), ('noone', 'No one')], default='registered', max_length=20)),
                ('allow_tagging', models.CharField(choices=[('everyone', 'Everyone'), ('registered', 'Registered users'), ('followers', 'Followers only'), ('noone', 'No one')], default='followers', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
