# Generated by Django 5.2.6 on 2026-10-03 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('poems', '0004_alter_poem_genre'),
        ('stories', '0008_alter_story_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoemImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='storyimpression',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('story', 'user'), name='unique_story_impression_per_user'),
        ),
        migrations.AddField(
            model_name='poemimpression',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='poems.poem'),
        ),
        migrations.AddField(
            model_name='poemimpression',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poem_impressions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='poemimpression',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('poem', 'user'), name='unique_poem_impression_per_user'),
        ),
    ]
