# Generated by Django 5.2.6 on 2026-07-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
