# Generated by Django 5.2.6 on 2026-09-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_poem_favorites_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
