# Generated by Django 5.2.6 on 2026-10-02 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_poem_is_private'),
        ('stories', '0008_alter_story_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='stories.genre'),
        ),
    ]
