# Generated by Django 5.2.6 on 2026-03-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
        ('stories', '0002_genre_rename_nsfw_story_is_mature_story_published_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
        migrations.AddField(
            model_name='genre',
            name='type',
            field=models.CharField(choices=[('story', 'Story'), ('poem', 'Poem')], db_index=True, default='story', max_length=10),
        ),
    ]
