# Generated by Django 5.2.6 on 2026-07-07 16:50

import django.db.models.deletion
from django.db import migrations, models


def create_initial_chapters(apps, schema_editor):
    Story = apps.get_model("stories", "Story")
    Chapter = apps.get_model("stories", "Chapter")
    database = schema_editor.connection.alias

    stories = Story.objects.using(database).filter(status="published").exclude(content="")
    for story in stories.iterator():
        if Chapter.objects.using(database).filter(story_id=story.pk).exists():
            continue
        if not story.content or not story.content.strip():
            continue
        Chapter.objects.using(database).create(
            story_id=story.pk,
            title=story.title,
            chapter_number=1,
            order=1,
            content=story.content,
        )
        Story.objects.using(database).filter(pk=story.pk).update(chapter_count=1)


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_rename_tag_tags_genre_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='chapter_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapter_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='stories.story')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('story', 'order')},
            },
        ),
        migrations.RunPython(create_initial_chapters, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='story',
            name='content',
        ),
    ]
