# Generated by Django 5.2.6 on 2026-09-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_chapter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
