# Generated by Django 5.2.6 on 2026-10-02 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_chapter_number_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='stories.genre'),
        ),
    ]
