# Generated by Django 6.0.2 on 2026-10-01 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_content_comment_chapter_likes'),
        ('poems', '0003_poem_is_private'),
        ('stories', '0007_chapter_number_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_views', to='poems.poem')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_views', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('poem__isnull', True), ('story__isnull', False)), models.Q(('poem__isnull', False), ('story__isnull', True)), _connector='OR'), name='content_view_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('story__isnull', False)), fields=('user', 'story'), name='unique_user_story_view'), models.UniqueConstraint(condition=models.Q(('poem__isnull', False)), fields=('user', 'poem'), name='unique_user_poem_view')],
            },
        ),
    ]
