# Generated by Django 6.0.2 on 2026-10-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_contentview'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contentview',
            name='content_view_exactly_one_target',
        ),
        migrations.RemoveConstraint(
            model_name='contentview',
            name='unique_user_story_view',
        ),
        migrations.RemoveConstraint(
            model_name='contentview',
            name='unique_user_poem_view',
        ),
        migrations.DeleteModel(
            name='ContentView',
        ),
    ]
